### PR TITLE
fix: Handle exceptions

### LINKED ISSUE #124: AppSecException unchecked exception is swallowed by Stream.map() when thrown
AppSecException is an unchecked exception. When thrown inside the [`OpenSourceVulnerabilityClient::queryBatch()`](https://github.com/vaadin/appsec-kit/blob/main/appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java#L64) method call during [`OpenSourceVulnerabilityService::getVulnerabilities()`](https://github.com/vaadin/appsec-kit/blob/main/appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityService.java#L59) method call it is swallowed by the `Stream::map()`.

Affected AppSec Kit versions: 1.0.0, 2.0.0, 3.0.0

### PR DESCRIPTION
**Pull request by sosa-vaadin**
## Description

If the OSV API throws an `IOException`, make sure that we at least log the error and don't break the AppSec Kit starter UI.

Fixes #124 

## Type of change

- [x] Bugfix

### CODE REVIEW

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java [hunk 1]
```diff
@@ -97,7 +97,17 @@ private Component buildScanNowButton() {
...
             lastScannedLabel.setText("Scanning...");
-            AppSecService.getInstance().scanForVulnerabilities();
+            UI ui = UI.getCurrent();
+            AppSecService.getInstance().scanForVulnerabilities()
+                    .exceptionally(ex -> {
+                        ui.access(() -> {
+                            lastScannedLabel
+                                    .setText("Error scanning vulnerabilities.");
+                            scanNowButton.setEnabled(true);
+                            LOGGER.error("Enabling button");
```
Comment (tamasmak) [inline appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java:107]: Could we log an error message about the failed manual scan and to add the exception too instead of "Enabling button"? Something similar what is in the `AppSecServiceInitListener`.

File: appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java [hunk 2]
```diff
@@ -45,7 +45,19 @@ class OpenSourceVulnerabilityClient {
...
+     *
+     * @param payload
+     *            the payload to send to OSV API server with all packages to
+     *            check.
+     * @return a response with a list of vulnerabilities.
+     * @throws AppSecException
+     *             if there is a connection issue with the OSV API server.
+     */
+    QueryBatchResponse queryBatch(QueryBatchRequestPayload payload)
+            throws AppSecException {
```
Comment (tamasmak) [inline appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java:60]: Should we add the `throws AppSecException` to the `queryVulnerability()` method too? It also uses the `createHttpURLConnection()`.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java [hunk 3]
```diff
@@ -37,7 +37,12 @@ public void serviceInit(ServiceInitEvent event) {
             appSecService.init();
             LOGGER.info("AppSec Kit initialized");
             appSecService.scanForVulnerabilities()
-                    .thenRun(appSecService::scheduleAutomaticScan);
+                    .exceptionally(appSecException -> {
+                        LOGGER.error(
+                                "Error scanning vulnerabilities. Automatic scan was not initiated.",
```
Comment (tamasmak) [inline appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java:42]: Scheduling of the automatic scan happens only after this scan for vulnerabilities. I think the `Automatic scan was not initiated.` message is not needed here. If the scheduling of the automatic scan fails it is logged [there](https://github.com/vaadin/appsec-kit/pull/133/files#diff-af76497ec7eb3b5edebf5b7fc6b9c6014a7b83c4b9e9d2b4605ced2496413a03R225).

**Comment by tamasmak** [comment]
Noticed that we could remove the "_or read_" from [this](https://github.com/vaadin/appsec-kit/pull/133/files#diff-4fb7ccfd6e5be5b061a28cd3b664de44dcb7f342009ee374b20fc99151169a30R110) exception message as there is no read timeout set for this connections anymore.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java (hunk 3 above)
Comment (sosa-vaadin) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java:42]: I believe we can just call `scheduleAutomaticScan()` since it has an initial delay of `0` if no scan has been done previously or the minimum time between scans has passed. That way we can remove the entire `exceptionally` block.

If we are keeping the first redundant scan for vulnerabilities, then I will just remove the last sentence of the log message.

File: appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java (hunk 2 above)
Comment (sosa-vaadin) [reply appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java:60]: Sure.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java (hunk 1 above)
Comment (sosa-vaadin) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/views/AppSecView.java:107]: Yeah, that log message was supposed to help me debug. It should've not been committed.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java (hunk 3 above)
Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java]: The vulnerability scan after each startup is needed because during application development dependencies can change. If the user adds or removes a dependency then after application startup we want to provide up-to-date information about vulnerabilities immediately and to not wait until next automatic scan.

Comment (sosa-vaadin) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecServiceInitListener.java]: Ok. Then I am just removing the last sentence.

**Comment by sosa-vaadin** [comment]
> Noticed that we could remove the "_or read_" from [this](https://github.com/vaadin/appsec-kit/blob/main/appsec-kit-backend/src/main/java/com/vaadin/appsec/backend/OpenSourceVulnerabilityClient.java#L98) exception message as there is no read timeout set for this connection anymore.

Changed the message to:
```
Connection to OSV API server has timed out
```

**Review by tamasmak — APPROVED** [review]
