### PR TITLE
Fix first vulnerabilities scan notification

### LINKED ISSUE #106: Scanner attached on every view/refresh
Appsec-kit attaching additional scanners on every view refresh. Which in turns fills the console log with snan messages. 

Expected: Scan runs only once per day or with "Scan now" functionality.
Actual: Scan runs after (almost) every navigation and/or view refresh. Additional scanners are connected and list after each scan becomes longer and longer. 

Reproduce with this example:
https://github.com/vaadin/hackathon-24-2/tree/herberts-and-kriss

Example of console log: 
`023-10-13T14:42:41.094+03:00  INFO 31780 --- [io-60278-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-10-13T14:42:41.176+03:00  INFO 31780 --- [io-60278-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2023-10-13T14:42:41.363+03:00  INFO 31780 --- [io-60278-exec-3] c.v.appsec.service.AppSecDevToolsPlugin  : Plugin connected
2023-10-13T14:42:46.588+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:42:46.700+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:42:58.146+03:00  INFO 31780 --- [io-60278-exec-1] c.v.appsec.service.AppSecDevToolsPlugin  : Plugin connected
2023-10-13T14:43:04.677+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:43:04.742+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:43:04.742+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:43:04.805+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:43:06.494+03:00  INFO 31780 --- [io-60278-exec-3] c.v.appsec.service.AppSecDevToolsPlugin  : Plugin connected
2023-10-13T14:43:57.077+03:00  INFO 31780 --- [io-60278-exec-8] c.v.appsec.service.AppSecDevToolsPlugin  : Plugin connected
2023-10-13T14:44:11.508+03:00  INFO 31780 --- [io-60278-exec-6] c.v.appsec.service.AppSecDevToolsPlugin  : Plugin connected
2023-10-13T14:44:17.965+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:44:18.027+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:44:18.027+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:44:18.092+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:44:18.092+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:44:18.156+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:44:18.156+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:44:18.219+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3
2023-10-13T14:44:18.219+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Scan completed
2023-10-13T14:44:18.284+03:00  INFO 31780 --- [pool-2-thread-1] c.v.appsec.service.AppSecDevToolsPlugin  : Vulnerabilities sent to the client: 3`

### PR DESCRIPTION
**Pull request by tamasmak**
- Adds the first vulnerability scan after init and removes the scan from the AppSec DevTools plugin
- Adds the AppSec DevTools plugin scan event listener only once
- Updates debug logging and messages

Closes #106

### CODE REVIEW

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java [hunk 1]
```diff
@@ -17,23 +17,22 @@ public class AppSecDevToolsPlugin implements DevToolsMessageHandler {
...
+        if (!scanEventListenerAdded) {
+            appSecService.addScanEventListener(scanEvent -> sendScanResult(
+                    scanEvent.getNewVulnerabilities().size(),
+                    devToolsInterface));
+            scanEventListenerAdded = true;
+            LOGGER.debug("Scan event listener added");
+        }
+        refreshScanResult(appSecService.getNewVulnerabilities().size(),
+                devToolsInterface);
     }
```
Comment (heruan) [inline appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:36]: This unfortunately can't work: while the `AppSecDevtoolsPlugin` instance is the same, the `handleConnect` might receive different `DevToolsInterface` objects (referring to different browsers) and we need to add the listener for each of them.

One possible solution could be to save a `<DevToolsInterface, Registration>` map, so we can also unregister the listeners when the plugin disconnects (or re-connects), e.g.

```suggestion
        if (!scanEventRegistrations.containsKey(devToolsInterface)) {
            Registration scanEventRegistration = appSecService
                    .addScanEventListener(event -> {
                        sendData("appsec-kit-scan",
                                event.getNewVulnerabilities().size(),
                                devToolsInterface);
                    });
            scanEventRegistrations.put(devToolsInterface,
                    scanEventRegistration);
        }

        sendData("appsec-kit-refresh",
                appSecService.getNewVulnerabilities().size(),
                devToolsInterface);
```

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java [hunk 2]
```diff
@@ -43,4 +42,24 @@ public boolean handleMessage(String command, JsonObject data,
...
         return true;
     }
+
+    private void sendScanResult(int vulnerabilityCount,
+            DevToolsInterface devToolsInterface) {
+        LOGGER.info("Scan completed");
+        sendData("appsec-kit-scan", vulnerabilityCount, devToolsInterface);
+        LOGGER.info(
+                "Vulnerabilities sent to the client: " + vulnerabilityCount);
+    }
```
Comment (heruan) [inline appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:52]: This is a one-liner method, no need for it if we move logging into `sendData`.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java [hunk 3]
```diff
@@ -43,4 +42,24 @@ public boolean handleMessage(String command, JsonObject data,
...
+
+    private void refreshScanResult(int vulnerabilityCount,
+            DevToolsInterface devToolsInterface) {
+        sendData("appsec-kit-refresh", vulnerabilityCount, devToolsInterface);
+    }
```
Comment (heruan) [inline appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:57]: This is another one-liner, no need for it.

**Review by heruan — CHANGES_REQUESTED** [review]

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java (hunk 2 above)
Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:52]: The goal is with the `sendScanResult` method to log only when a "real" scan happens and not on every `handleConnect` method call (e.g. page refresh, new window and new tab). The `refreshScanResult` method's purpose is to keep the message with the vulnerability count (basically send it again) in the AppSec Kit tab after the page is refreshed or new window or tab is opened.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java (hunk 1 above)
Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:36]: Good point. In this case I will use the suggested solution.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java (hunk 3 above)
Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:57]: I agree. I can refactor this.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java (hunk 1 above)
Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java:36]: Tried this solution and on each page refresh, new window and new tab a new `DevToolsInterface` object is created and added to the `scanEventRegistrations`. There is no possibility to remove the old ones because there is no plugin disconnected (or re-connected) mechanism to use (there are no events about these).

Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java]: I [committed](https://github.com/vaadin/appsec-kit/pull/113/commits/ded79f450941f63df5239a4fe0d549854ed3dcba) this solution for testing purpose.

File: appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java (hunk 2 above)
Comment (heruan) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java]: I understand the reason now, thanks! The idea to log the message only upon scan completion makes sense, but the method anyway is used only in one place (the lambda) so I'd still put it back there: since it does not have nested blocks or complex structure, having a separate method does not improve readability but instead force the reader to look for the method 👀

Comment (heruan) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java]: Also, I'd switch to `debug` logging for this messages. WDYT?

Comment (tamasmak) [reply appsec-kit-starter/src/main/java/com/vaadin/appsec/service/AppSecDevToolsPlugin.java]: Also, based on the new scan event listener tracking, I removed the `appsec-kit-refresh` command to always use the `appsec-kit-scan`.

**Review by heruan — APPROVED** [review]
